CREATE TABLE [dbo].[NET]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FitnessScore] DECIMAL(18, 9) NOT NULL DEFAULT 0,
	[BirthGeneration] INT NOT NULL DEFAULT 0,
	[BatchId] INT NOT NULL,
	[Enabled] BIT NOT NULL DEFAULT 1,
    CONSTRAINT [FK_NET_Batch] FOREIGN KEY ([BatchId]) REFERENCES [Batch]([Id]),
)

GO

CREATE TRIGGER [dbo].[DeleteNet]
ON [dbo].[NET]
INSTEAD OF DELETE
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM [dbo].[Connection] WHERE [NetworkId] IN (SELECT [Id] FROM DELETED)
	DELETE FROM [dbo].[Node] WHERE [NetworkId] IN (SELECT [Id] FROM DELETED)
	DELETE FROM [dbo].[NET] WHERE [Id] IN (SELECT [Id] FROM DELETED)
END